name: Feature Request
description: Have a new idea or feature request
title: "[FEATURE REQUEST] <description here>"
labels: [feature-request]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature request, idea
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add (multiple) screenshot links (if applicable)
    validations:
      required: false
  - type: textarea
    id: Describe the solution you did like
    attributes:
      label: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: Describe alternatives you've considered
    attributes:
      label: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context about the feature request here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://iter.hackclub.com/discord)
        Feel free to check out other cool repositories of the Hack Club ITER [here](https://github.com/hackclubiter)
